voxel_size: 0.05
truncation_distance_factor: 3.0 #15 #3.0
max_ray_length_m: 10
max_weight: 10
use_sparsity_compensation_factor: true

object_tracking:
  enable: false
  icp_use_reciprocal_correspondences: false
  icp_max_correspondence_distance: 10
  icp_use_symmetric_objective: false
  icp_max_iterations: 5
  icp_transformation_epsilon: 0.0002
  icp_absolute_mse: 0.000000001
  icp_euclidean_fitness_epsilon: 0.01 # 0.01 = improvement of 1% of previous MSE.

meshing:
  update_mesh_every_n_sec: 10.0
  publish_mesh: true
  mesh_filename: "main_map.ply"

visualizer:
  enable: false
  camera_intrinsics: [462.1379497504639, 0.0, 320.5, 0.0, 462.1379497504639, 240.5, 0.0, 0.0, 1.0] #[564.3, 0, 480, 0, 564.3, 270, 0, 0, 1]

debug:
  verbose_log: false
